# Whether to log more output.
# The CLI flag -v/--verbose will override this.
verbose: false
# Whether to surrender as soon as possible.
# To farm regular League pass EXP (that has tokens) it is recommended to leave this on false,
# since the repeating mission gives out EXP based on playtime and winning (being top 4).
# To farm TFT pass EXP it is recommended to set this to true,
# since the TFT pass receives a flat 100 EXP per normal tft game played, regardless of any other factors.
# The CLI flag -f/--ffearly will override this.
forfeit_early: false

# The traits you want the bot to roll for.
# The trait names are almost as written in-game, with spaces replaced by _ and . and : being ignored.
# For example: admin, star_guardian, mecha_prime, lasercorps
# For a full list, visit https://github.com/Kyrluckechuck/TFT-Bot/tree/main/captures/trait
wanted_traits:
  - duelist
  - brawler

# By default, the bot only looks for the next trait in the list if the trait that comes
# before has been found. So a brawler unit will only be bought after a duelist unit has
# been bought.
# You can disable that behavior by setting this to false, which will equally attempt
# to buy all traits.
purchase_traits_in_prioritized_order: true

# Override where League is installed.
# The only reason you would set this is if all of these conditions apply:
# 1. You're initially starting the bot while the League Client is closed
# 2. You want the bot to start the League Client for you
# 3. The bot is unable to determine the League installation path by itself
override_install_location: ''

# Version of the YAML. Changing this manually can potentially break the bot, so don't!
version: 2
