# The level to log information at. The higher the level, the less you will see.
# We do not recommend setting it higher than WARNING, but support it.
# Valid levels: DEBUG, INFO, WARNING, ERROR, CRITICAL
# The CLI flag -v/--verbose will override this to DEBUG.
log_level: "INFO"
# Whether to surrender as soon as possible.
# To farm regular League pass EXP (that has tokens) it is recommended to leave this on false,
# since the repeating mission gives out EXP based on playtime and winning (being top 4).
# To farm TFT pass EXP it is recommended to set this to true,
# since the TFT pass receives a flat 100 EXP per normal tft game played, regardless of any other factors.
# The CLI flag -f/--ffearly will override this.
forfeit_early: false

# The traits you want the bot to roll for.
# The trait names are almost as written in-game, with spaces replaced by _ and . and : being ignored.
# For example: admin, star_guardian, mecha_prime, lasercorps
# For a full list, visit https://github.com/Kyrluckechuck/TFT-Bot/tree/main/captures/trait
wanted_traits:
  - duelist
  - brawler

# By default, the bot only looks for the next trait in the list if the trait that comes
# before has been found. So a brawler unit will only be bought after a duelist unit has
# been bought.
# You can disable that behavior by setting this to false, which will equally attempt
# to buy all traits.
purchase_traits_in_prioritized_order: true

# Settings for the bots decisions made for purchasing units, leveling and rolling.
economy:
  # The mode itself to be used. ocr_* modes require Tesseract-OCR to be installed.
  # "default" constantly spends all gold, cycling equally between purchasing, leveling, and rolling.
  # "ocr_standard" tries to keep your gold at around 50, otherwise behaves like default.
  mode: "default"
  # Override the automatic detection of tesseract. Should not be needed, but is supported.
  override_tesseract_location: ""

# Configure the various timeouts the bot uses throughout it's looping logic.
# Adjust these to account for differences in internet/hardware speed.
# All of these are measured in seconds.
timeouts:
  # Time we wait to check for any updates.
  update_notifier: 10
  # Time we wait to find the league client process to exist.
  league_client: 300
  # Time we wait for us to successfully connect to the league client.
  client_connect: 60
  # Time we wait for the client to tell us that it's done loadin.
  client_availability: 120
  # Time we wait between a match being marked as started and the game showing up.
  game_window: 30
  # Time we wait for the load screen to finish.
  game_start: 120
  # Time we wait for the exit button after being dead.
  exit_button: 25
  # Time we wait for the fall-back method to work if no exit button is found.
  graceful_exit: 60
  # Time to wait AT LEAST before surrendering, after we detected that we can.
  surrender_min: 60
  # Time to wait AT MOST before surrendering.
  surrender_max: 90

# Override where League is installed.
# The only reason you would set this is if all of these conditions apply:
# 1. You're initially starting the bot while the League Client is closed
# 2. You want the bot to start the League Client for you
# 3. The bot is unable to determine the League installation path by itself
override_install_location: ''

# Version of the YAML. Changing this manually can potentially break the bot, so don't!
version: 5
